### ISSUE TITLE
Crash on opening the About menu

### ISSUE THREAD

**Issue by mpeter50** [you-apps/TranslateYou#424] opened 2024-04-26 22:11 UTC
### Steps to reproduce

1. Open app
2. Open 3 dots menu at the top right
3. Tap "About"

### Expected behavior

The About menu opens

### Actual behavior

The app has crashed.

### Translate You version

9.0, F-droid official repo

### Android version

Android 6

### Other details

Log messages from around the crash:
```
04-27 00:05:29.746 14027 14027 W ResourceType: Failure getting entry for 0x7f070094 (t=6 e=148) (error -75)
04-27 00:05:29.756 14027 14027 D AndroidRuntime: Shutting down VM
04-27 00:05:29.756 14027 14027 D scoop   : uncaughtExceptionHook (com.bnyro.translate): Sending broadcast
04-27 00:05:29.764 14027 14027 D scoop   : uncaughtExceptionHook (com.bnyro.translate): Broadcast already sent
04-27 00:05:29.765 14027 14027 D scoop   : uncaughtExceptionHook (com.bnyro.translate): Broadcast already sent
04-27 00:05:29.767 14027 14027 E AndroidRuntime: FATAL EXCEPTION: main
04-27 00:05:29.767 14027 14027 E AndroidRuntime: Process: com.bnyro.translate, PID: 14027
04-27 00:05:29.767 14027 14027 E AndroidRuntime: android.content.res.Resources$NotFoundException: Resource ID #0x7f070094
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at android.content.res.Resources.getValue(Resources.java:1369)
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at android.content.res.MiuiResources.getValue(MiuiResources.java:145)
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at s5.m.d2(SourceFile:7)
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at androidx.compose.material3.z6.e(SourceFile:683)
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at androidx.compose.material3.z6.b0(SourceFile:36)
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at n0.b.a(SourceFile:51)
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at n0.b.b0(SourceFile)
04-27 00:05:29.767 14027 14027 E AndroidRuntime:        at t.i.W(SourceFile:182)
```

If you need a more complete trace, I have that but thats a little more complicated to transfer from my phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-06-01 13:34
Please share a crash log while using a debuggable build from the app, you can find these under the actions tab on GitHub.

**Comment by drogga** [comment] 2024-06-02 08:56
I couldn't find artifacts there...

**Comment by mpeter50** [comment] 2024-06-03 19:33
Indeed, I can't find artifacts either. Maybe their visibility is restricted?
Do you also have the same isssue @drogga ?

**Comment by mpeter50** [comment] 2024-06-03 20:12
Built the APK in Android Studio with libreDebug build variant at tag v9.0 (3bbc2dbe09d8928529df00ebe9f46556aebc5146).

This is the crash log when opening the about menu in this build:
https://gist.github.com/mpeter50/fe6ed158cdd4fb5e7011c67ff52824e6

Also, I have just noticed that you have added the "cant reproduce tag" soon after I have opened the issue.
Can I set up github somehow to notify me when my issues' tags have changed? I'm receiving email notifications for ~everything I receive normal github notifications for, and its not rare that it would be useful. A quick look didnt reveal any such setting.

**Comment by drogga** [comment] 2024-06-04 12:06
I don't think you can restrict or hide the visibility of the artifacts, @Bnyro probably didn't even check before suggesting...

No, it didn't crash for me there, the last time I used it on the device it's installed on, on my daily driver (the one I typing from currently) I use either the Translate app by Google, MS or Yandex, there are things in them I don't like and  none of them are perfect, but they are way more reliable than any of the open source projects I tested, or for that matter - any app that is not owned by a big company, like the 3 above, but at least their's have a pop-up window while called from the context menu of a text, can open in landscape and don't constantly throw network, API or whatever errors, like this one, no matter which engine is being used (I don't use API keys), but just always work and are always reliable.

GitHub notifications system needs a lot of work, the site as well, it doesn't notify you about certain things, but it does wrongly for others, AFAIK you can't set it up to notify you about changes in the Tags, nor edits by others with privileges of your issues/comments, like changed title or content, but it does modify the edited timestamp of the issue.

**Comment by mpeter50** [comment] 2024-06-04 12:11
> I don't think you can restrict or hide the visibility of the artifacts, @Bnyro probably didn't even check before suggesting...

The reason I ask is I remember something about them being limited by default. But maybe its something else, never used the feature as a repo owner.

> and don't constantly throw network, API or whatever errors

thruth be told, I only rarely translate on my phone, and often it was unstable for me too in that way too

**Comment by Bnyro** [comment] 2024-07-15 10:40
You need to be logged in to be able to download CI builds.

They exist for all actions that have the CI label, e.g. https://github.com/you-apps/TranslateYou/actions/runs/9732206435.

**Comment by mpeter50** [comment] 2024-07-18 20:15
Here is a crash log made with the build of [this action](https://github.com/you-apps/TranslateYou/actions/runs/9732206435): https://gist.github.com/mpeter50/ed3a49dd749bf2544a594ca0074b2a1a

**Comment by drogga** [comment] 2024-07-19 05:50
You don't have to include the date, timestamp PID (twice) and letters in the logs ;), but even tho I don't understand logs much - I guess it's the compose issue (I have the same with latest 2 vers. of "InstallWithOptions" by Zacharee), if true, Google needs to fix it, but I might be terribly wrong, so you can completely ignore this comment if that's the case.

**Comment by mpeter50** [comment] 2024-07-19 14:45
> You don't have to include the date, timestamp PID (twice) and letters in the logs

I was just copying it from the logcat without modification, did not realize it might be in the way. If it is, let me know and I'll remove it from later logs.
Though, I think the timestamp and the letter (indicating the log level) is useful. The PID is twice because the 2nd is the Thread ID, and the main thread's ID is the PID.

**Comment by Bnyro** [comment] 2024-09-21 15:04
Unfortunately this looks like an Android issue (looking at the crash log).

Since it's not reproducible on other devices, I'm closing this issue.

**Closed by Bnyro** 2024-09-21 15:04 UTC
Labels: bug, can't reproduce
