### ISSUE TITLE
Deepl server error

### ISSUE THREAD

**Issue by tr1ckert** [you-apps/TranslateYou#308] opened 2023-08-04 14:58 UTC
### Steps to reproduce

I entered my free API key for deepl into the app, chose to use the free API and went back.

Small message at the bottom saying the app can't communicate with the server.

No VPN or Adblocker enabled.
OnePlus 11 with Android 13

Wifi or mobile data make no difference.

Tried all versions from 3.9 and upwards.

Cleared data multiple times on the latest version.

### Expected behavior

Translation of text

### Actual behavior

![Screenshot_2023-08-04-16-38-36-27_fbcdf42ed509c3884e299b0f88be1eba](https://github.com/Bnyro/TranslateYou/assets/17404930/59ba399f-892f-4ff4-a437-6075310f5871)
![IMG_20230804_163830](https://github.com/Bnyro/TranslateYou/assets/17404930/185c986b-332b-4b95-b940-5b8e61605db5)

### Translate You version

6.3

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-04 15:43
The API is untested from my side since I don't want to create a DeepL account personally.
Therefore, I can't help here unfortunately.

**Comment by lollocosta123** [comment] 2023-08-14 11:12
I had the same issue for like 15 minutes after creating the new API key. Now after waiting it seems to work fine.

**Comment by tr1ckert** [comment] 2023-08-14 13:44
> I had the same issue for like 15 minutes after creating the new API key. Now after waiting it seems to work fine.

Ok, super weird, but now it works.
Especially weird because before even downloading the Translate You app I downloaded a Windows app that also uses the API key: https://github.com/LAB02-Research/DeepL-Translator

And there it worked instantly.

**Comment by Bnyro** [comment] 2023-09-25 07:07
Closing, since it seems to generally work.

**Closed by Bnyro** 2023-09-25 07:07 UTC
Labels: bug, help wanted

**Comment by 7eter** [comment] 2023-10-04 18:23
I can confirm: after restarting (and also clearing cache) it works fine!
